sudo: required
services:
  - docker

before_install:
  - docker build -t ssrikanth/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true ssrikanth/react-test npm test

after_success:
  - docker run -t ssrikanth/multi-client ./client
  - docker run -t ssrikanth/multi-client-nginx ./nginx
  - docker run -t ssrikanth/multi-client-server ./server
  - docker run -t ssrikanth/multi-client-worker ./worker